<div class="htmlArea">
<?=
$this->rcmRichEdit(
    'html',
    '<img alt="" src="/modules/rcm/images/no-image.png"><p>Lorem ipsum dolor sit amet,consectetur adipiscing elit. Pellentesque justosapien, convallis vehicula sollicitudin tristique, rhoncus velenim.Maecenas mollis dignissim urna, something about monkeys et mollis augue tempus nec. Proin a orcinulla. Pellentesque laoreet orci vitaenisl viverra imperdiet.</p>',
    'div',
    array('style' => 'width:100%')
); ?>
</div>
